name: Build Goodbirds Maps

on:
  schedule:
    # 12:00 ET and 21:00 ET - convert to UTC
    # During EDT (UTC-4): 12:00 ET -> 16:00 UTC, 21:00 ET -> 01:00 UTC next day
    - cron: "0 16 * * *"
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: docs/maps
      LOGO_BASENAME: goodbirds_logo_test.png
      MAP_LOGO_FILE: ${{ github.workspace }}/docs/goodbirds_logo_test.png

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure docs and maps directories exist
        run: |
          mkdir -p docs/maps

      - name: Copy logo to docs
        run: |
          if [ -f "${{ env.LOGO_BASENAME }}" ]; then
            cp "${{ env.LOGO_BASENAME }}" "docs/${{ env.LOGO_BASENAME }}"
          else
            echo "Logo not found at repo root - ${LOGO_BASENAME}"
          fi

      - name: Build map(s)
        env:
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
          OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
          MAP_LOGO_FILE: ${{ env.MAP_LOGO_FILE }}
        run: |
          python scripts/build_map.py

      - name: Rebuild archive index.html with bigger header logo
        run: |
          python - <<'PY'
          import os, re
          from pathlib import Path
          DOCS = Path("docs")
          MAPS = DOCS / "maps"
          DOCS.mkdir(exist_ok=True)
          MAPS.mkdir(exist_ok=True)

          files = sorted([p for p in MAPS.glob("ebird_radius_map_*.html")], reverse=True)
          by_day = {}
          for p in files:
            m = re.search(r"ebird_radius_map_(\d{4}-\d{2}-\d{2})_(\d{2}-\d{2}-\d{2})_ET_(\d+)km\.html$", p.name)
            if not m:
              continue
            day = m.group(1)
            time = m.group(2).replace("-", ":")
            by_day.setdefault(day, []).append((time, p.name))

          day_keys = sorted(by_day.keys(), reverse=True)[:7]
          by_day = {k: by_day[k] for k in day_keys}

          logo = "goodbirds_logo_test.png"
          header = f"""
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Goodbirds - Notable Maps Archive</title>
            <style>
              body {{
                font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
                margin: 0;
                padding: 0 0 40px 0;
                background: #fafafa;
                color: #222;
              }}
              .wrap {{
                max-width: 900px;
                margin: 0 auto;
                padding: 20px 16px 40px 16px;
              }}
              .header {{
                display: flex;
                align-items: center;
                gap: 20px;
                margin-bottom: 16px;
                border-bottom: 1px solid #ddd;
                padding-bottom: 16px;
              }}
              .header img {{
                height: 220px; /* large logo for legibility */
              }}
              .title h1 {{
                font-size: 32px;
                margin: 0 0 6px 0;
              }}
              .title p {{
                margin: 6px 0 0 0;
                font-size: 16px;
                color: #444;
              }}
              .day {{
                margin-top: 24px;
              }}
              .day h2 {{
                font-size: 20px;
                margin: 0 0 10px 0;
              }}
              ul {{
                list-style: none;
                padding-left: 0;
                margin: 0;
              }}
              li {{
                margin: 5px 0;
              }}
              a {{
                text-decoration: none;
                color: #0a58ca;
              }}
              a:hover {{
                text-decoration: underline;
              }}
              .latest-link {{
                margin-top: 8px;
              }}
            </style>
          </head>
          <body>
            <div class="wrap">
              <div class="header">
                <img src="{logo}" alt="Goodbirds logo">
                <div class="title">
                  <h1>Goodbirds - Notable Maps Archive</h1>
                  <p>Updated twice daily - data from the eBird Notable API - maps generated with Folium - credits in repository.</p>
                  <div class="latest-link"><a href="maps/latest.html">View the latest map</a></div>
                </div>
              </div>
          """

          sections = []
          for day in sorted(by_day.keys(), reverse=True):
            items = []
            for time, fname in sorted(by_day[day], reverse=True):
              items.append(f'<li><a href="maps/{fname}">{day} {time} ET</a></li>')
            sections.append(f'<div class="day"><h2>{day}</h2><ul>' + "\n".join(items) + "</ul></div>")

          footer = """
              </div>
            </body>
          </html>
          """

          html = header + "\n".join(sections) + footer
          (DOCS / "index.html").write_text(html, encoding="utf-8")
          print("Wrote docs/index.html")
          PY

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Automated map build - update maps and archive"
            git push
          else
            echo "No changes to commit."
          fi
