name: Build Goodbirds Maps

on:
  schedule:
    - cron: "0 16 * * *"   # 12:00 pm ET
    - cron: "0 1 * * *"    # 9:00 pm ET
  workflow_dispatch:
    inputs:
      force:
        description: "Force rebuild"
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
      OUTPUT_DIR: docs/maps
      KEEP_COUNT: "30"
      # Expose the logo file path to the script
      MAP_LOGO_FILE: ${{ github.workspace }}/docs/goodbirds_logo_text.png
      # For timestamping in title if you ever want fixed slots
      RUN_DATE_ET: ${{ github.event.schedule != '' && fromJSON('null') || '' }}
      RUN_SLOT: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium requests branca

      - name: Build maps
        run: |
          mkdir -p docs/maps
          python scripts/build_map.py

      - name: Rebuild archive index
        run: |
          # Simple index writer that keeps last 7 days of links and shows a bigger header logo
          python - << 'PY'
          import os, re, datetime, pathlib
          docs = pathlib.Path("docs")
          maps_dir = docs/"maps"
          files = sorted([f for f in maps_dir.glob("ebird_radius_map_*.html")], reverse=True)
          # Group by date prefix
          groups = {}
          for f in files:
              m = re.match(r"ebird_radius_map_(\d{4}-\d{2}-\d{2})_", f.name)
              if not m: 
                  continue
              groups.setdefault(m.group(1), []).append(f.name)
          # Keep only last 7 days
          by_day = sorted(groups.items(), reverse=True)[:7]

          html = []
          html.append("<!doctype html><html><head><meta charset='utf-8'><title>Goodbirds Map Archive</title>")
          html.append("<meta name='viewport' content='width=device-width, initial-scale=1'>")
          html.append("<style>")
          html.append("body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;margin:20px;}")
          html.append("h1{font-size:20px;margin:0 0 2px 0}")
          html.append(".day{margin: 12px 0 18px 0}")
          html.append(".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:8px}")
          html.append("a{color:#0645ad;text-decoration:none} a:hover{text-decoration:underline}")
          html.append("</style></head><body>")
          # Bigger logo in header
          html.append("<header style='display:flex;align-items:center;gap:12px;margin-bottom:12px;'>")
          html.append("<img src='goodbirds_logo_text.png' alt='Goodbirds' style='height:64px;'>")
          html.append("<div>")
          html.append("<h1>Goodbirds — Notable eBird Maps</h1>")
          html.append("<div>Updated twice daily — data: eBird API — credits in map footer</div>")
          html.append("</div></header>")
          for day, entries in by_day:
              html.append(f"<div class='day'><div style='font-weight:700;margin-bottom:6px'>{day}</div>")
              html.append("<div class='grid'>")
              for name in sorted(entries, reverse=True):
                  html.append(f"<a href='maps/{name}'>{name}</a>")
              html.append("</div></div>")
          html.append("</body></html>")
          (docs/"index.html").write_text("\n".join(html), encoding="utf-8")
          PY

      - name: Commit and publish
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/maps/*.html docs/index.html || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update maps and archive index"
            git push
          fi
