name: Build bird maps at 12:00 and 21:00 ET (EDT only)

on:
  schedule:
    - cron: "0 16 * * *"   # 12:00 PM EDT (UTC-4)
    - cron: "0 1 * * *"    # 9:00 PM EDT (UTC-4) next-day UTC
  workflow_dispatch:
    inputs:
      FORCE_BUILD:
        description: "Run immediately (uses nearest slot label)"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine intended slot
        id: slot
        run: |
          force="${{ github.event.inputs.FORCE_BUILD }}"
          run_slot=""
          run_date_et=$(TZ=America/New_York date +'%Y-%m-%d')
          if [ "$force" = "true" ]; then
            hour=$(TZ=America/New_York date +'%H')
            if [ "$hour" -ge 6 ] && [ "$hour" -lt 18 ]; then
              run_slot="12"
            else
              run_slot="21"
            fi
          else
            trig="${{ github.event.schedule }}"
            if [ "$trig" = "0 16 * * *" ]; then
              run_slot="12"
            elif [ "$trig" = "0 1 * * *" ]; then
              run_slot="21"
              run_date_et=$(TZ=America/New_York date -d 'yesterday' +'%Y-%m-%d')
            else
              echo "Unexpected schedule: $trig"
              exit 1
            fi
          fi
          echo "run_slot=$run_slot" >> $GITHUB_OUTPUT
          echo "run_date_et=$run_date_et" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate map
        env:
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
          OUTPUT_DIR: ${{ github.workspace }}/docs/maps
          KEEP_COUNT: "30"
          RUN_DATE_ET: ${{ steps.slot.outputs.run_date_et }}
          RUN_SLOT: ${{ steps.slot.outputs.run_slot }}
          MAP_LOGO_FILE: ${{ github.workspace }}/docs/goodbirds_logo_text.png   # <-- add this
        run: |
          mkdir -p "$OUTPUT_DIR"
          python scripts/build_map.py

      - name: Rebuild archive index (bigger logo, objective text, last 7 days, no indent)
        run: |
          set -euo pipefail
          mkdir -p docs
          # All map files with ET timestamp in name
          files=$(ls -1 docs/maps/ebird_radius_map_*_ET_*km.html 2>/dev/null | sort -r || true)

          # Collect unique ET dates from filenames (desc), keep only most recent 7
          mapfile -t all_dates < <(for f in $files; do
            b=$(basename "$f")
            d=$(echo "$b" | awk -F'_' '{print $4}' | sed 's/[^0-9-]//g')
            echo "$d"
          done | awk '!seen[$0]++')
          # Trim to 7 dates
          keep_dates=("${all_dates[@]:0:7}")

          # Build index.html
          cat > docs/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>eBird Notable Maps Archive</title>
          <style>
            body{font-family:sans-serif;margin:2rem;max-width:900px}
            h1{font-size:1.8rem;margin:0 0 .75rem 0;display:flex;align-items:center;gap:.75rem}
            .logo{height:80px} /* bigger logo */
            h2{font-size:1.15rem;margin:1.1rem 0 .4rem 0;color:#333}
            /* Remove left-indent for lists; make all days align flush left */
            ul{margin:.25rem 0 .9rem 0; padding-left:0}
            li{list-style:none; line-height:1.6}
            .latest{margin:.75rem 0 1rem 0;font-size:1.05rem}
            .note{color:#555}
          </style>
          <h1>
            <img src="goodbirds_logo_text.png" alt="Goodbirds logo" class="logo">
            eBird Notable Maps
          </h1>
          <div class="latest"><strong><a href="maps/latest.html">Open Latest Map</a></strong></div>

          <p class="note">
            Maps are scheduled to build automatically at <strong>12:00</strong> and <strong>21:00</strong> New York time.
            Each map visualizes recent <strong>eBird “Notable” observations</strong> near the selected center point.
          </p>
          <p class="note">
            Built with the <strong>eBird API</strong>, <strong>Python</strong>, <strong>Folium</strong> (Leaflet),
            <strong>GitHub Actions</strong>, and <strong>GitHub Pages</strong>.
          </p>
          HTML

          # Write sections for the last 7 ET dates only
          if [ ${#keep_dates[@]} -gt 0 ]; then
            for d in "${keep_dates[@]}"; do
              pretty=$(TZ=America/New_York date -d "$d" +'%A, %b %d, %Y')
              echo "<h2>$pretty</h2>" >> docs/index.html
              echo "<ul>" >> docs/index.html
              # list files for this date in reverse-chronological order
              for f in $files; do
                base=$(basename "$f")
                dp=$(echo "$base" | awk -F'_' '{print $4}' | sed 's/[^0-9-]//g')
                if [ "$dp" = "$d" ]; then
                  echo "<li><a href=\"maps/$base\">$base</a></li>" >> docs/index.html
                fi
              done
              echo "</ul>" >> docs/index.html
            done
          fi

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "Archive page: larger logo, objective text, last 7 days, no indent"
          default_author: github_actions
