name: Build bird maps at 12:00 and 21:00 ET (EDT only)

on:
  schedule:
    - cron: "0 16 * * *"   # 12:00 PM EDT (UTC-4)
    - cron: "0 1 * * *"    # 9:00 PM EDT (UTC-4) next-day UTC
  workflow_dispatch:
    inputs:
      FORCE_BUILD:
        description: "Set to true to run immediately (uses nearest slot label)"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine intended slot
        id: slot
        run: |
          force="${{ github.event.inputs.FORCE_BUILD }}"
          run_slot=""
          run_date_et=$(TZ=America/New_York date +'%Y-%m-%d')
          if [ "$force" = "true" ]; then
            hour=$(TZ=America/New_York date +'%H')
            if [ "$hour" -ge 6 ] && [ "$hour" -lt 18 ]; then
              run_slot="12"
            else
              run_slot="21"
            fi
          else
            trig="${{ github.event.schedule }}"
            if [ "$trig" = "0 16 * * *" ]; then
              run_slot="12"
            elif [ "$trig" = "0 1 * * *" ]; then
              run_slot="21"
              run_date_et=$(TZ=America/New_York date -d 'yesterday' +'%Y-%m-%d')
            else
              echo "Unexpected schedule: $trig"
              exit 1
            fi
          fi
          echo "run_slot=$run_slot" >> $GITHUB_OUTPUT
          echo "run_date_et=$run_date_et" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate map
        env:
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
          OUTPUT_DIR: ${{ github.workspace }}/docs/maps
          KEEP_COUNT: "30"
          RUN_DATE_ET: ${{ steps.slot.outputs.run_date_et }}
          RUN_SLOT: ${{ steps.slot.outputs.run_slot }}
        run: |
          mkdir -p "$OUTPUT_DIR"
          python scripts/build_map.py

      - name: Ensure logo asset is present for archive and maps
        run: |
          mkdir -p docs
          if [ -f goodbirds_logo_test.png ]; then
            cp -f goodbirds_logo_test.png docs/
          fi

      - name: Rebuild archive index with big logo
        run: |
          set -euo pipefail
          mkdir -p docs
          files=$(ls -1 docs/maps/ebird_radius_map_*_ET_*km.html 2>/dev/null | sort -r || true)

          cat > docs/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>eBird Notable Maps Archive</title>
          <style>
            body{font-family:sans-serif;margin:2rem;max-width:980px}
            header{display:flex;align-items:center;gap:14px;margin-bottom:1rem}
            .logo{height:120px} /* bigger logo as requested */
            h1{font-size:1.9rem;margin:0}
            h2{font-size:1.2rem;margin:1.2rem 0 .3rem 0;color:#333}
            ul{line-height:1.6;margin:.2rem 0 .8rem 1rem}
            .latest{margin:.5rem 0 1rem 0;font-size:1.05rem}
            .note{color:#555}
            .datehdr{margin-top:1.25rem;border-top:1px solid #eee;padding-top:.75rem}
            a{text-decoration:none}
          </style>
          <header>
            <img src="goodbirds_logo_test.png" alt="Goodbirds logo" class="logo">
            <div>
              <h1>eBird Notable Maps</h1>
              <div class="latest"><strong><a href="maps/latest.html">Open Latest Map</a></strong></div>
              <div class="note">Built automatically at 12:00 and 21:00 New York time.</div>
            </div>
          </header>
          <p style="max-width:65ch;line-height:1.5;margin:.25rem 0 1.25rem 0;color:#333;">
            <strong>About:</strong> Goodbirds is a vibe coding project to nudge everyone to step outside and find a good bird near them.
            Maps are generated twice a day from eBird notable reports. Moving soon to <a href="https://goodbirds.org" target="_blank" rel="noopener">goodbirds.org</a>.
          </p>
          HTML

          last_date=""
          for f in $files; do
            base=$(basename "$f")
            date_part=$(echo "$base" | awk -F'_' '{print $4}' | sed 's/[^0-9-]//g')
            if [ "$date_part" != "$last_date" ]; then
              pretty=$(TZ=America/New_York date -d "$date_part" +'%A, %b %d, %Y')
              [ -n "$last_date" ] && echo "</ul>" >> docs/index.html
              echo "<h2 class=\"datehdr\">$pretty</h2><ul>" >> docs/index.html
              last_date="$date_part"
            fi
            echo "<li><a href=\"maps/$base\">$base</a></li>" >> docs/index.html
          done
          [ -n "$files" ] && echo "</ul>" >> docs/index.html

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs"
          message: "Archive header logo, map title logo, grouped archive"
          default_author: github_actions
